---
title: "Clustering Mezcla Gaussiana"
author: "JairES"
format: html
editor: visual
---

## Mclust

Se utiliza la librería mclust para clustering/clasificación a partir de modelos de mezcla Gaussiana.

## Criterio de Información Bayesiana

---

```{r}
datos = read.csv("../outputs/rasters_as_matrix.csv")
datos[is.na(datos)]=0
datos_prueba = datos
BIC2 <- mclustBIC(datos_prueba,G = 6:15,modelNames = c("EEI","EEV","EEE"))##Tarda

```

```{r}
mod1_2 <- Mclust(datos, x = BIC2)
s = summary(mod1, parameters = TRUE)
# 998 renglones y 978 columnas rellenar por renglones
clasificacion = s$classification
clasificacion = clasificacion[-((length(clasificacion) - 35): length(clasificacion))]
clasificacion = as.numeric(clasificacion)
matriz_clasificacion = matrix(as.array(clasificacion), nrow = 998, ncol = 978, byrow = TRUE)
library(raster)
raster_data <- raster(matriz_clasificacion)
raster_extent <- extent(raster_data)
color_palette <- terrain.colors(100) 
plot(raster_data, col=rainbow(15), main="Raster pv_refri1.tif")
plot(shapefile, add=TRUE, col="white", border="red")
writeRaster(raster_data, "")
```
